### ISSUE TITLE
 В рядку що біжить замість української І ти Ї якась хрінь!

### ISSUE THREAD

**Issue by Creo2005** [alvikskor/FieryLedLampUKR#1]
Замість великої Ї - З чи 3-ка

**Comment by alvikskor** [comment]
Усунена проблема з виведенням рядком, що біжить, деяких символів :  Ї,ї,Є.є.І.і.Ё.ё . Користуйтесь с задоволенням. Дякую за запитання.

**Comment by alvikskor** [comment]
Усунена проблема з виведенням рядком, що біжить, деяких символів : Ї,ї,Є.є.І.і.Ё.ё . Користуйтесь с задоволенням. Дякую за запитання.
